apis:
  discord:
    client_id:    ''
    secret_token: ''

bot:
  senpai:  000000
  storage: './storage/'
  version: 'v0.0.1'

messages:
  commands:
    hello_world:  'Konnichiwa, Senpai.'
    laughatshi:   'https://media3.giphy.com/media/h2HTvVuKVS4daQaVuS/giphy.gif'
    logchannel:   'Your logging channel has been set to: '
    shutdown:     'Oyasuminasai, Senpai'
